# Generated by Django 2.2.5 on 2019-09-21 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masege_app', '0002_studentunion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('ptitle', models.CharField(max_length=64)),
                ('pcontent', models.TextField()),
                ('view_cnt', models.IntegerField()),
                ('like_cnt', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('ssex', models.BooleanField(default=True)),
                ('sinst', models.CharField(max_length=30)),
                ('sdept', models.CharField(max_length=30)),
                ('sclass', models.CharField(max_length=30)),
                ('avatar', models.ImageField(default='uploads_imgs/default.jpg', upload_to='uploads_imgs/')),
                ('signature', models.CharField(default='The quick brown fox jumps over the lazy dog.', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='studentUnion',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='posts',
            name='pauth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masege_app.Student'),
        ),
    ]
